services:
  cs2-bot:
    image: ghcr.io/beaudenison/cs2-server-bot:latest
    container_name: cs2-server-bot
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - cs2bot_data:/data

volumes:
  cs2bot_data:
